name: docker bastion
on: 
  workflow_dispatch:
jobs:
  docker-bastion:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout code
      uses: actions/checkout@v5
    - name: checking files
      run: ls -la



